baseurl = "/"
languageCode = "en-us"
title = "Homepage"
[languages]
	[languages.en]
		baseURL = "https://amazing-fermi-6e7f97.netlify.com"
		languageName = "English"
		title = "In English"
		weight = 1
	[languages.nl]
		baseURL = "https://amazing-fermi-6e7f97.netlify.com/nl"
		languageName = "Nederlands"
		title = "In het Nederlands"
		weight = 2